[package]
name = "runt"
version = "0.1.0"
authors = ["Todd Mortimer <todd@opennet.ca>"]

[dependencies]

imap = "1.0.2"
regex = "1.3.1"
native-tls = "0.2.3"
toml = "0.5.5"
serde = "1.0.104"
serde_derive = "1.0.104"
dirs = "2.0.2"
maildir = "0.3.4"

#[patch.crates-io]
#imap = { path = "/home/todd/code/runt/deps/rust-imap" }
#imap-proto = { path = "/home/todd/code/runt/deps/imap-proto" }
#openssl-sys = { path = "/home/todd/code/runt/deps/rust-openssl/openssl-sys" }
#maildir = { path = "/home/todd/code/runt/deps/maildir" }
